import { GraphTopologyDefinition } from "./graph-types";

export const BUILT_IN_GRAPH_TOPOLOGIES: GraphTopologyDefinition[] = [
  {
    id: "supervisor_worker_critic",
    name: "Supervisor-Worker-Critic StateGraph",
    tagline: "Autonomous multi-agent orchestration with cyclical self-correction loops",
    description: "Hierarchical LangGraph topology where a Central Supervisor plans sub-tasks, dispatches to Research and Synthesizer workers, and submits results to an Adversarial Critic. If rigor < 85%, state loops back with critique feedback.",
    category: "Multi-Agent",
    defaultObjective: "Research modern Model Context Protocol (MCP) server integration patterns with Gemini 3.8 and synthesize an enterprise architecture blueprint.",
    nodes: [
      {
        id: "START",
        name: "Entry State",
        type: "entry",
        description: "Initializes AgentState with user objective and context bounds.",
        iconName: "Play",
        position: { x: 50, y: 180 },
      },
      {
        id: "supervisor",
        name: "Central Supervisor",
        type: "supervisor",
        description: "Deconstructs the objective, inspects active state, and routes execution to workers.",
        iconName: "Compass",
        position: { x: 220, y: 180 },
      },
      {
        id: "research_worker",
        name: "MCP Research Worker",
        type: "worker",
        description: "Executes MCP tools (Google Docs, Web Search, GitHub) to retrieve factual context.",
        iconName: "Search",
        position: { x: 420, y: 80 },
      },
      {
        id: "synthesizer",
        name: "Solution Synthesizer",
        type: "synthesizer",
        description: "Compiles research findings and drafts a comprehensive, production-grade technical response.",
        iconName: "Cpu",
        position: { x: 620, y: 180 },
      },
      {
        id: "adversarial_critic",
        name: "Adversarial Critic",
        type: "critic",
        description: "Evaluates the draft for accuracy, completeness, and rigor (0-100%). Enforces conditional loop if < 85%.",
        iconName: "ShieldAlert",
        position: { x: 820, y: 180 },
      },
      {
        id: "action_dispatcher",
        name: "Action Dispatcher",
        type: "action",
        description: "Executes automated external dispatch (WhatsApp receipt, GitHub PR, Gmail notification).",
        iconName: "Send",
        position: { x: 1020, y: 180 },
      },
      {
        id: "END",
        name: "Terminal State",
        type: "end",
        description: "Finalizes AgentState, logs telemetry, and seals execution trace.",
        iconName: "CheckCircle2",
        position: { x: 1200, y: 180 },
      },
    ],
    edges: [
      { id: "e1", source: "START", target: "supervisor", label: "Initialize" },
      { id: "e2", source: "supervisor", target: "research_worker", label: "Route Task" },
      { id: "e3", source: "research_worker", target: "synthesizer", label: "Context Findings" },
      { id: "e4", source: "synthesizer", target: "adversarial_critic", label: "Submit Draft" },
      {
        id: "e5_loop",
        source: "adversarial_critic",
        target: "synthesizer",
        label: "Rigor < 85% (Self-Correction Loop)",
        isConditional: true,
        conditionLabel: "Critique Score < 85%",
      },
      {
        id: "e6_pass",
        source: "adversarial_critic",
        target: "action_dispatcher",
        label: "Rigor >= 85% (Approved)",
        isConditional: true,
        conditionLabel: "Critique Score >= 85%",
      },
      { id: "e7", source: "action_dispatcher", target: "END", label: "Complete Workflow" },
    ],
  },
  {
    id: "self_correcting_coder",
    name: "Self-Correcting Code Generation Graph",
    tagline: "Compile-check, type-verification, and iterative test-driven generation",
    description: "LangGraph state machine for software development. Translates user requirements into typed TypeScript/Python code, passes it through static verification, and iteratively resolves compiler warnings until zero faults remain.",
    category: "Code-Refinement",
    defaultObjective: "Generate a type-safe MCP Tool handler for Google Knowledge Graph queries with comprehensive error boundaries in TypeScript.",
    nodes: [
      {
        id: "START",
        name: "Requirement Ingestion",
        type: "entry",
        description: "Parse requirements and type signatures.",
        iconName: "FileCode",
        position: { x: 50, y: 180 },
      },
      {
        id: "code_architect",
        name: "Code Architect",
        type: "supervisor",
        description: "Designs the type schema, interface contracts, and module boundaries.",
        iconName: "Layers",
        position: { x: 250, y: 180 },
      },
      {
        id: "code_generator",
        name: "Implementation Generator",
        type: "synthesizer",
        description: "Writes the actual implementation code with full type definitions.",
        iconName: "Terminal",
        position: { x: 500, y: 180 },
      },
      {
        id: "linter_verifier",
        name: "Linter & Type Verifier",
        type: "critic",
        description: "Validates AST syntax, type assertions, and edge-case error boundaries.",
        iconName: "CheckSquare",
        position: { x: 750, y: 180 },
      },
      {
        id: "END",
        name: "Production Ready Artifact",
        type: "end",
        description: "Deploys code artifact to repository workspace.",
        iconName: "Sparkles",
        position: { x: 1000, y: 180 },
      },
    ],
    edges: [
      { id: "e1", source: "START", target: "code_architect", label: "Spec" },
      { id: "e2", source: "code_architect", target: "code_generator", label: "Contract" },
      { id: "e3", source: "code_generator", target: "linter_verifier", label: "Verify" },
      {
        id: "e4_refine",
        source: "linter_verifier",
        target: "code_generator",
        label: "Type Errors Found (Refine)",
        isConditional: true,
        conditionLabel: "Lints > 0",
      },
      {
        id: "e5_pass",
        source: "linter_verifier",
        target: "END",
        label: "Zero Errors (Pass)",
        isConditional: true,
        conditionLabel: "Lints == 0",
      },
    ],
  },
  {
    id: "cognitive_council_graph",
    name: "Cognitive Council Multi-Perspective Graph",
    tagline: "5-member parallel cognitive consensus aggregation",
    description: "Evaluates high-stakes strategic, technical, and ethical dilemmas by fanning out state to 5 specialized archetype nodes simultaneously and aggregating via a consensus voting reduction.",
    category: "Strategic-Synthesis",
    defaultObjective: "Should we migrate from monolithic architecture to distributed event-driven microservices?",
    nodes: [
      {
        id: "START",
        name: "Dilemma Ingestion",
        type: "entry",
        description: "Captures strategic dilemma and stakeholder context.",
        iconName: "HelpCircle",
        position: { x: 50, y: 220 },
      },
      {
        id: "fanout_dispatcher",
        name: "Fan-Out Dispatcher",
        type: "supervisor",
        description: "Dispatches problem to all 5 Council Archetypes in parallel.",
        iconName: "Share2",
        position: { x: 220, y: 220 },
      },
      {
        id: "rationalist_node",
        name: "The Rationalist (Speed-RAG)",
        type: "worker",
        description: "Evaluates vector recall and deterministic proofs.",
        iconName: "Binary",
        position: { x: 450, y: 60 },
      },
      {
        id: "adversary_node",
        name: "The Adversary (GAN Stress)",
        type: "worker",
        description: "Evaluates perturbation vulnerabilities and failure points.",
        iconName: "ShieldAlert",
        position: { x: 450, y: 140 },
      },
      {
        id: "temporal_node",
        name: "The Temporal Synthesizer (RNN)",
        type: "worker",
        description: "Evaluates 18-month trajectory and technology velocity.",
        iconName: "History",
        position: { x: 450, y: 220 },
      },
      {
        id: "guardian_node",
        name: "The Value Guardian (RLHF)",
        type: "worker",
        description: "Evaluates constitutional alignment and privacy guardrails.",
        iconName: "Lock",
        position: { x: 450, y: 300 },
      },
      {
        id: "consensus_reducer",
        name: "Executive Consensus Reducer",
        type: "synthesizer",
        description: "Synthesizes all 5 verdicts into a unified actionable roadmap.",
        iconName: "Scale",
        position: { x: 720, y: 220 },
      },
      {
        id: "END",
        name: "Deliberation Sealed",
        type: "end",
        description: "Stores certified council decision to audit ledger.",
        iconName: "FileCheck",
        position: { x: 920, y: 220 },
      },
    ],
    edges: [
      { id: "e1", source: "START", target: "fanout_dispatcher", label: "Dilemma" },
      { id: "e2", source: "fanout_dispatcher", target: "rationalist_node", label: "Logic" },
      { id: "e3", source: "fanout_dispatcher", target: "adversary_node", label: "Stress" },
      { id: "e4", source: "fanout_dispatcher", target: "temporal_node", label: "Temporal" },
      { id: "e5", source: "fanout_dispatcher", target: "guardian_node", label: "RLHF" },
      { id: "e6", source: "rationalist_node", target: "consensus_reducer", label: "Verdict" },
      { id: "e7", source: "adversary_node", target: "consensus_reducer", label: "Verdict" },
      { id: "e8", source: "temporal_node", target: "consensus_reducer", label: "Verdict" },
      { id: "e9", source: "guardian_node", target: "consensus_reducer", label: "Verdict" },
      { id: "e10", source: "consensus_reducer", target: "END", label: "Consensus" },
    ],
  },
];
